version: "2"
services:
  nginx:
    image: nginx:latest
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ${BASE_PATH}${PROJECT_PATH}/php/app:/site
      - ${BASE_PATH}${PROJECT_PATH}/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpfpm
  phpfpm:
#    image: phpdockerio/php7-fpm
    build: ./php/
    volumes:
      - ${BASE_PATH}${PROJECT_PATH}/php/app:/site
    links:
      - database
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
